# Generated by Django 5.1.4 on 2026-06-10 17:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('kind', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer')], default='expense', max_length=20)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='organisations.organisation')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'transaction_categories',
                'ordering': ('kind', 'name'),
                'indexes': [models.Index(fields=['org', 'kind'], name='transaction_org_id_b0bd5d_idx'), models.Index(fields=['org', 'parent'], name='transaction_org_id_5da50d_idx')],
                'unique_together': {('org', 'slug')},
            },
        ),
    ]
