# Generated by Django 5.1.4 on 2026-06-10 16:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('low_balance', 'Low Balance'), ('overdue_invoice', 'Overdue Invoice'), ('fx_movement', 'FX Rate Movement'), ('large_outflow', 'Large Upcoming Outflow'), ('anomaly', 'Unusual Transaction'), ('consent_expiry', 'Bank Connection Expiring'), ('forecast_warning', 'Forecast Warning')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('low_balance_threshold', models.DecimalField(decimal_places=2, default=5000, max_digits=15)),
                ('large_outflow_threshold', models.DecimalField(decimal_places=2, default=2000, max_digits=15)),
                ('overdue_days_threshold', models.PositiveIntegerField(default=7)),
                ('fx_movement_percent', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('email_daily_digest', models.BooleanField(default=True)),
                ('email_weekly_digest', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'alert_settings',
            },
        ),
    ]
