# Generated by Django 5.1.4 on 2026-06-10 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='organisations.organisation'),
        ),
        migrations.AddField(
            model_name='alertsettings',
            name='org',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_settings', to='organisations.organisation'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['org', 'is_read', '-created_at'], name='alerts_org_id_fd433d_idx'),
        ),
    ]
