# Generated by Django 5.1.4 on 2026-06-10 16:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('forecast_flag', models.CharField(choices=[('healthy', 'Healthy'), ('watch', 'Watch'), ('warning', 'Warning'), ('critical', 'Critical')], default='healthy', max_length=20)),
                ('daily_briefing', models.TextField()),
                ('cash_position_summary', models.TextField(blank=True)),
                ('top_risk', models.JSONField(blank=True, null=True)),
                ('opportunities', models.JSONField(default=list)),
                ('chase_list', models.JSONField(default=list)),
                ('fx_alert', models.TextField(blank=True)),
                ('week_ahead', models.TextField(blank=True)),
                ('raw_response', models.JSONField(default=dict)),
                ('generation_cost_tokens', models.PositiveIntegerField(default=0)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='organisations.organisation')),
            ],
            options={
                'db_table': 'ai_insights',
                'ordering': ['-generated_at'],
            },
        ),
    ]
