# Generated by Django 5.1.4 on 2026-06-11 03:31

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('normalised_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('type', models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('employee', 'Employee'), ('lender', 'Lender'), ('tax_authority', 'Tax Authority'), ('other', 'Other')], default='other', max_length=20)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
                ('country_code', models.CharField(blank=True, default='', max_length=2)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_auto_created', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='counterparties.counterparty')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterparties', to='organisations.organisation')),
            ],
            options={
                'verbose_name_plural': 'counterparties',
                'db_table': 'counterparties',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['org', 'type'], name='counterpart_org_id_0f7734_idx'), models.Index(fields=['org', 'normalised_name'], name='counterpart_org_id_bf11f5_idx')],
            },
        ),
    ]
