# Generated by Django 5.1.4 on 2026-06-10 16:09

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('truelayer_transaction_id', models.CharField(max_length=255, unique=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('merchant_name', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('supplier_payment', 'Supplier Payment'), ('customer_receipt', 'Customer Receipt'), ('payroll', 'Payroll'), ('tax', 'Tax'), ('rent_overhead', 'Rent / Overhead'), ('fx_transfer', 'FX Transfer'), ('bank_fee', 'Bank Fee'), ('loan_repayment', 'Loan Repayment'), ('other', 'Other')], default='other', max_length=100)),
                ('category_overridden', models.BooleanField(default=False)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_group_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.bankaccount')),
            ],
            options={
                'db_table': 'transactions',
                'indexes': [models.Index(fields=['account', '-timestamp'], name='transaction_account_8c9e8d_idx'), models.Index(fields=['category'], name='transaction_categor_45fcdd_idx'), models.Index(fields=['is_recurring', 'recurring_group_id'], name='transaction_is_recu_805cc9_idx')],
            },
        ),
    ]
