# Generated by Django 5.1.4 on 2026-06-11 03:31

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
        ('categories', '0001_initial'),
        ('counterparties', '0001_initial'),
        ('organisations', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_categor_45fcdd_idx',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='truelayer_transaction_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='base_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='base_currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='confidence',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=4),
        ),
        migrations.AddField(
            model_name='transaction',
            name='counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='counterparties.counterparty'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='dedup_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='transaction',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fx_rate',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='org',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='organisations.organisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('bank_feed', 'Bank Feed'), ('accounting_api', 'Accounting Platform'), ('document', 'Document Extraction'), ('csv_import', 'CSV Import'), ('manual', 'Manual Entry')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.bankaccount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['org', '-timestamp'], name='transaction_org_id_500237_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['org', 'source'], name='transaction_org_id_505037_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('org', 'source', 'external_id'), name='uniq_external_id_per_org_source'),
        ),
    ]
