# Generated by Django 5.1.4 on 2026-06-10 16:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('industry', models.CharField(choices=[('import_export', 'Import / Export'), ('wholesale', 'Wholesale'), ('retail', 'Retail'), ('manufacturing', 'Manufacturing'), ('construction', 'Construction'), ('hospitality', 'Hospitality / Food & Beverage'), ('technology', 'Technology / SaaS'), ('professional_services', 'Professional Services'), ('logistics', 'Logistics / Transport'), ('agriculture', 'Agriculture'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('services', 'Other Services'), ('other', 'Other')], default='other', max_length=100)),
                ('country_code', models.CharField(blank=True, default='', help_text='ISO 3166-1 alpha-2, e.g. GB, US, AE, TR', max_length=2)),
                ('base_currency', models.CharField(default='USD', help_text='ISO 4217 currency code', max_length=3)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('locale', models.CharField(default='en', help_text='BCP 47 locale for number/date formatting, e.g. en-GB, ar-AE', max_length=10)),
                ('is_demo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'organisations',
            },
        ),
        migrations.CreateModel(
            name='OrgMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('viewer', 'Viewer'), ('accountant', 'Accountant (external)')], default='owner', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organisations.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'org_memberships',
                'unique_together': {('user', 'org')},
            },
        ),
    ]
