# Generated by Django 5.1.4 on 2026-06-10 16:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('horizon_days', models.PositiveIntegerField(default=90)),
                ('algorithm_version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='running', max_length=50)),
                ('metadata', models.JSONField(default=dict)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_runs', to='organisations.organisation')),
            ],
            options={
                'db_table': 'forecast_runs',
            },
        ),
        migrations.CreateModel(
            name='ForecastScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('parameters', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forecasting.forecastrun')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='organisations.organisation')),
            ],
            options={
                'db_table': 'forecast_scenarios',
            },
        ),
        migrations.CreateModel(
            name='ForecastDataPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('forecast_date', models.DateField()),
                ('predicted_inflow', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('predicted_outflow', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('predicted_net', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('predicted_balance', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('confidence_score', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('confidence_band_low', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('confidence_band_high', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('committed_inflow', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('committed_outflow', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('layer_breakdown', models.JSONField(default=dict)),
                ('committed_items', models.JSONField(default=list)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='forecasting.forecastrun')),
            ],
            options={
                'db_table': 'forecast_data_points',
                'indexes': [models.Index(fields=['run', 'forecast_date'], name='forecast_da_run_id_5b7f0b_idx')],
                'unique_together': {('run', 'forecast_date')},
            },
        ),
    ]
