# Generated by Django 5.1.4 on 2026-07-15 13:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0002_invoice'),
        ('forecasting', '0001_initial'),
        ('organisations', '0001_initial'),
        ('transactions', '0002_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('written_off', 'Written Off')], default='unpaid', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='counterparties.counterparty')),
                ('matched_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_bills', to='transactions.transaction')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='organisations.organisation')),
            ],
            options={
                'db_table': 'bills',
                'indexes': [models.Index(fields=['status', 'due_date'], name='bills_status_due_idx'), models.Index(fields=['counterparty'], name='bills_counterparty_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecurringObligation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('payroll', 'Payroll'), ('rent', 'Rent / Lease'), ('loan', 'Loan Repayment'), ('other', 'Other Recurring')], default='other', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Every 2 Weeks'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=20)),
                ('anchor_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('anchor_weekday', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('manual', 'Manually Entered'), ('detected', 'Detected (Phase 4)')], default='manual', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_obligations', to='counterparties.counterparty')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_obligations', to='organisations.organisation')),
            ],
            options={
                'db_table': 'recurring_obligations',
                'indexes': [models.Index(fields=['org', 'is_active'], name='recurobl_org_active_idx')],
            },
        ),
    ]
