# Generated by Django 5.1.4 on 2026-06-10 16:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.TextField()),
                ('original_filename', models.CharField(max_length=500)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('bank_statement', 'Bank Statement'), ('receipt', 'Receipt'), ('cheque', 'Cheque'), ('purchase_order', 'Purchase Order'), ('other', 'Other')], default='other', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending — queued for processing'), ('preprocessing', 'Preprocessing image'), ('extracting', 'Extracting data'), ('review', 'Awaiting human review'), ('confirmed', 'Confirmed — data committed'), ('rejected', 'Rejected by user'), ('failed', 'Processing failed')], default='pending', max_length=30)),
                ('processing_tier_used', models.SmallIntegerField(blank=True, choices=[(1, 'Tier 1 — PDF text (free)'), (2, 'Tier 2 — Haiku text'), (3, 'Tier 3 — Haiku vision'), (4, 'Tier 4 — Sonnet vision')], null=True)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('processing_error', models.TextField(blank=True)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('confirmed_data', models.JSONField(blank=True, null=True)),
                ('created_invoice_id', models.UUIDField(blank=True, null=True)),
                ('created_transaction_id', models.UUIDField(blank=True, null=True)),
                ('created_customer_id', models.UUIDField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='organisations.organisation')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='documents.document')),
            ],
            options={
                'db_table': 'document_line_items',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='DocumentStorageSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('backend', models.CharField(choices=[('local', 'Local filesystem — stored on this server'), ('s3', 'AWS S3 / Cloudflare R2 / DigitalOcean Spaces'), ('supabase', 'Supabase Storage')], default='local', max_length=20)),
                ('s3_bucket', models.CharField(blank=True, max_length=255)),
                ('s3_region', models.CharField(blank=True, max_length=50)),
                ('s3_access_key_encrypted', models.TextField(blank=True)),
                ('s3_secret_key_encrypted', models.TextField(blank=True)),
                ('s3_endpoint_url', models.URLField(blank=True, help_text='Leave blank for AWS. Set for R2/DO Spaces.')),
                ('supabase_url', models.URLField(blank=True)),
                ('supabase_bucket', models.CharField(blank=True, max_length=255)),
                ('supabase_key_encrypted', models.TextField(blank=True)),
                ('configured_at', models.DateTimeField(auto_now=True)),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_settings', to='organisations.organisation')),
            ],
            options={
                'db_table': 'document_storage_settings',
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['org', 'status'], name='documents_org_id_38cb85_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['org', 'document_type'], name='documents_org_id_c1f0ad_idx'),
        ),
    ]
