# Generated by Django 5.1.4 on 2026-06-10 16:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('payment_terms_days', models.PositiveIntegerField(default=30)),
                ('risk_score', models.CharField(choices=[('green', 'Green — pays on time'), ('amber', 'Amber — occasionally late'), ('red', 'Red — chronic late payer')], default='green', max_length=10)),
                ('avg_days_late', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('risk_updated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='organisations.organisation')),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('written_off', 'Written Off')], default='unpaid', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='customers.customer')),
                ('matched_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_invoices', to='transactions.transaction')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='organisations.organisation')),
            ],
            options={
                'db_table': 'invoices',
                'indexes': [models.Index(fields=['status', 'due_date'], name='invoices_status_73cf28_idx'), models.Index(fields=['customer'], name='invoices_custome_ba8289_idx')],
            },
        ),
    ]
