# Generated by Django 5.1.4 on 2026-06-10 16:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FxAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_currency', models.CharField(default='GBP', max_length=3)),
                ('quote_currency', models.CharField(max_length=3)),
                ('threshold_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('direction', models.CharField(choices=[('up', 'Strengthens'), ('down', 'Weakens'), ('either', 'Either direction')], default='either', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fx_alerts', to='organisations.organisation')),
            ],
            options={
                'db_table': 'fx_alerts',
            },
        ),
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_currency', models.CharField(max_length=3)),
                ('quote_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=15)),
                ('source', models.CharField(choices=[('exchangerate-api', 'ExchangeRate-API'), ('alpha_vantage', 'Alpha Vantage')], max_length=50)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fx_rates',
                'indexes': [models.Index(fields=['base_currency', 'quote_currency', '-fetched_at'], name='fx_rates_base_cu_e9024c_idx')],
            },
        ),
    ]
