# Generated by Django 5.1.4 on 2026-06-10 16:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_id', models.CharField(blank=True, max_length=100)),
                ('provider_name', models.CharField(blank=True, max_length=255)),
                ('access_token_encrypted', models.TextField()),
                ('refresh_token_encrypted', models.TextField()),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('consent_expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('error', 'Error')], default='active', max_length=50)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_connections', to='organisations.organisation')),
            ],
            options={
                'db_table': 'bank_connections',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('truelayer_account_id', models.CharField(max_length=255, unique=True)),
                ('account_type', models.CharField(blank=True, choices=[('TRANSACTION', 'Current / Transaction'), ('SAVINGS', 'Savings'), ('CREDIT_CARD', 'Credit Card'), ('MERCHANT', 'Merchant')], max_length=50)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('account_number', models.CharField(blank=True, max_length=20)),
                ('sort_code', models.CharField(blank=True, max_length=10)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('available_balance', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('balance_updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='banking.bankconnection')),
            ],
            options={
                'db_table': 'bank_accounts',
            },
        ),
        migrations.CreateModel(
            name='DirectDebit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('truelayer_mandate_id', models.CharField(max_length=255, unique=True)),
                ('merchant_name', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='monthly', max_length=20)),
                ('day_of_month', models.SmallIntegerField(blank=True, null=True)),
                ('next_payment_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_debits', to='banking.bankaccount')),
            ],
            options={
                'db_table': 'direct_debits',
            },
        ),
    ]
